AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# ----- Parameter設定 -----
Parameters:
  ProvisionedConcurrentCount:
    Type: Number
    Default: 1
Conditions:
  ProvisionedConcurrency: !Not [!Equals [!Ref ProvisionedConcurrentCount, 0]]
# ----- ここまで -----

Globals:
  Function:
    Timeout: 5

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      # ---- 同時実行数設定 -----
      AutoPublishAlias: live # Alias必須
      ProvisionedConcurrencyConfig: !If
        - ProvisionedConcurrency
        - ProvisionedConcurrentExecutions: !Ref ProvisionedConcurrentCount # 第2引数でExcutionsの設定
        - !Ref "AWS::NoValue" #
      # ---- ここまで -----
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
